[package]
name = "pseudo_random"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

keywords = ["pseudo_random"]
description = "pseudo random number generator"
license = "MIT"
readme = "README.md"
repository = "https://github.com/nathanfaucett/rs-pseudo_random.git"
homepage = "https://github.com/nathanfaucett/rs-pseudo_random"

[profile.dev]
debug-assertions = false

[profile.release]
debug-assertions = false

[profile.test]
debug-assertions = false

[profile.bench]
debug-assertions = false

[profile.doc]
debug-assertions = false

[dependencies]
