[package]
name = "pseudo_random"
version = "0.1.0"
authors = ["nathanfaucett <nathanfaucett@gmail.com>"]

[profile.dev]
debug-assertions = false

[profile.release]
debug-assertions = false

[profile.test]
debug-assertions = false

[profile.bench]
debug-assertions = false

[profile.doc]
debug-assertions = false

[dependencies]
